/*
 * 389. Find the Difference
 * Problem Link: https://leetcode.com/problems/find-the-difference/
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * Return the letter that was added to t.
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 */
//Beats 40% | TC = O(NlogN), TC of Arrays.sort is O(NlogN)
// class Solution {
//     public char findTheDifference(String s, String t) {
//         char [] sChar = s.toCharArray();
//         char [] tChar = t.toCharArray();
//         Arrays.sort(sChar);
//         Arrays.sort(tChar);
//         for(int i=0; i<sChar.length; i++){
//             if(sChar[i] != tChar[i])    return tChar[i];
//         }
//         return tChar[tChar.length-1];
//     }
// }

// Can be done using HashMap storing 26 characters and their count and returning the character with 1 extra count.

//Beats 99.63% | Using Bit Manipulation-XOR | TC = O(N) 
class Solution {
    public char findTheDifference(String s, String t) {
        char c = 0;
        for (char ch : s.toCharArray())
            c ^= ch;
        for (char ch : t.toCharArray())
            c ^= ch;
        return c;
    }
}